---
- hosts: spark
  remote_user: phoenix
  tasks:
      - name: Prepare SPARK_HOME directory
        become: yes
        file:
            state: directory
            path: "{{ spark_home }}"
            mode: 01755

      - name: Unarchive spark to SPARK_HOME
        become: yes
        unarchive:
            remote_src: yes
            src: https://www-eu.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz
            dest: "{{ spark_home }}"

      - name: Register SPARK_HOME
        become: yes
        lineinfile:
            path: /etc/profile
            regexp: '^export SPARK_HOME='
            line: "export SPARK_HOME={{ spark_home }}/spark-2.4.0-bin-hadoop2.7"

      - name: Register PATH
        become: yes
        lineinfile:
            path: /etc/profile
            regexp: '^export PATH=${SPARK_HOME}/bin'
            line: 'export PATH=${SPARK_HOME}/bin:$PATH'

      - name: Prepare spark environment file
        become: yes
        file:
            state: touch
            path: "{{ spark_home }}/spark-2.4.0-bin-hadoop2.7/conf/spark-env.sh"
            mode: 0755

      - name: Configure spark environment
        become: yes
        lineinfile:
            path: "{{ spark_home }}/spark-2.4.0-bin-hadoop2.7/conf/spark-env.sh"
            regexp: "^JAVA_HOME="
            line: "JAVA_HOME={{ java_home }}/jdk1.8.0_191"

      - name: Configure spark environment
        become: yes
        lineinfile:
            path: "{{ spark_home }}/spark-2.4.0-bin-hadoop2.7/conf/spark-env.sh"
            regexp: "^SPARK_HOME="
            line: "SPARK_HOME={{ spark_home }}/spark-2.4.0-bin-hadoop2.7"

