---
- hosts: java
  remote_user: phoenix
  tasks:
      - name: Prepare JAVA_HOME directory
        become: yes
        file:
            state: directory
            path: "{{ java_home }}"
            mode: 01755

      - name: Unarchive JDK to JAVA_HOME
        become: yes
        unarchive:
            remote_src: no
            src: binaries/jdk-8u191-linux-x64.tar.gz
            dest: "{{ java_home }}"

      - name: Register JAVA_HOME
        become: yes
        lineinfile:
            path: /etc/profile
            regexp: '^export JAVA_HOME='
            line: "export JAVA_HOME={{ java_home }}/jdk1.8.0_191"

      - name: Register JRE_HOME
        become: yes
        lineinfile:
            path: /etc/profile
            regexp: '^export JRE_HOME='
            line: 'export JRE_HOME=${JAVA_HOME}/jre'


      - name: Register CLASSPATH
        become: yes
        lineinfile:
            path: /etc/profile
            regexp: '^export CLASSPATH='
            line: 'export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib'


      - name: Register PATH
        become: yes
        lineinfile:
            path: /etc/profile
            regexp: '^export PATH='
            line: 'export PATH=${JAVA_HOME}/bin:$PATH'

